/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Francisco Delgado Martínez
 */
public class ListaUTRM extends javax.swing.JFrame {
    
    ListaEstudiante Lista = new ListaEstudiante();

    /**
     * Creates new form ListaUTRM
     */
    public ListaUTRM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListaTxt = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        ApellidoPTxt = new javax.swing.JTextField();
        GuardarInicioBtn = new javax.swing.JButton();
        ApellidoMTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TotalTxt = new javax.swing.JTextArea();
        MatriculaTxt = new javax.swing.JTextField();
        NombreTxt = new javax.swing.JTextField();
        CantidadBtn = new javax.swing.JButton();
        CarreraTxt = new javax.swing.JTextField();
        OrdenarBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BuscarBtn = new javax.swing.JButton();
        BuscarTxt = new javax.swing.JTextField();
        GuardarFinalBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListaTxt.setColumns(20);
        ListaTxt.setRows(5);
        jScrollPane1.setViewportView(ListaTxt);

        jLabel1.setText("Apellido Paterno");

        GuardarInicioBtn.setText("Guardar Inicio");
        GuardarInicioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarInicioBtnActionPerformed(evt);
            }
        });

        TotalTxt.setColumns(20);
        TotalTxt.setRows(5);
        jScrollPane2.setViewportView(TotalTxt);

        CantidadBtn.setText("Cantidad");
        CantidadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadBtnActionPerformed(evt);
            }
        });

        OrdenarBtn.setText("Enlistar");
        OrdenarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenarBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Apellido Materno");

        jLabel6.setText("Total de Estudiantes.");

        jLabel3.setText("Matricula");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Lista de Estudiantes de la UTRM");

        jLabel4.setText("Nombre");

        jLabel5.setText("Carrera");

        BuscarBtn.setText("Buscar Alumno");
        BuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarBtnActionPerformed(evt);
            }
        });

        GuardarFinalBtn.setText("Guardar Final");
        GuardarFinalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarFinalBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(ApellidoMTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(ApellidoPTxt)
                    .addComponent(MatriculaTxt)
                    .addComponent(NombreTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CarreraTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GuardarInicioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GuardarFinalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addGap(62, 62, 62))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(CantidadBtn)
                                            .addGap(89, 89, 89))))
                                .addContainerGap(71, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BuscarTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BuscarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(OrdenarBtn)
                        .addGap(163, 163, 163))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(17, 17, 17)
                .addComponent(OrdenarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ApellidoPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ApellidoMTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MatriculaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(BuscarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarreraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CantidadBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GuardarInicioBtn)
                        .addGap(18, 18, 18)
                        .addComponent(GuardarFinalBtn)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarInicioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarInicioBtnActionPerformed
        // TODO add your handling code here:
        Alumno alum = new Alumno();
        alum.setApellidoP(this.ApellidoPTxt.getText());
        alum.setApellidoM(this.ApellidoMTxt.getText());
        alum.setNombre(this.NombreTxt.getText());
        alum.setMatricula(Integer.parseInt(this.MatriculaTxt.getText()));
        alum.setCarrera(this.CarreraTxt.getText());

        Nodo nuevo = new Nodo(alum);
        this.Lista.saveInicio(nuevo);
        this.ApellidoPTxt.setText("");
        this.ApellidoMTxt.setText("");
        this.NombreTxt.setText("");
        this.MatriculaTxt.setText("");
        this.CarreraTxt.setText("");
        this.ListaTxt.setText(this.Lista.imprimirListaInicio());
    }//GEN-LAST:event_GuardarInicioBtnActionPerformed

    private void CantidadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadBtnActionPerformed
        // TODO add your handling code here:
        this.TotalTxt.setText("Hay " + this.Lista.CantidadAlumnos() + " estudiantes hasta ahora.");
    }//GEN-LAST:event_CantidadBtnActionPerformed

    private void OrdenarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenarBtnActionPerformed
        // TODO add your handling code here:
        this.ListaTxt.setText(this.Lista.enlistarAlumnos());
    }//GEN-LAST:event_OrdenarBtnActionPerformed

    private void BuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarBtnActionPerformed
        // TODO add your handling code here:
        int matri;
        matri = Integer.parseInt(this.BuscarTxt.getText());
        Lista.buscarMatricula(matri);
    }//GEN-LAST:event_BuscarBtnActionPerformed

    private void GuardarFinalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarFinalBtnActionPerformed
        // TODO add your handling code here:
        Alumno alum = new Alumno();
        alum.setApellidoP(this.ApellidoPTxt.getText());
        alum.setApellidoM(this.ApellidoMTxt.getText());
        alum.setNombre(this.NombreTxt.getText());
        alum.setMatricula(Integer.parseInt(this.MatriculaTxt.getText()));
        alum.setCarrera(this.CarreraTxt.getText());

        Nodo nuevo = new Nodo(alum);
        this.Lista.saveFinal(nuevo);
        this.ApellidoPTxt.setText("");
        this.ApellidoMTxt.setText("");
        this.NombreTxt.setText("");
        this.MatriculaTxt.setText("");
        this.CarreraTxt.setText("");
        this.ListaTxt.setText(this.Lista.imprimirListaFinal());
    }//GEN-LAST:event_GuardarFinalBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaUTRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaUTRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaUTRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaUTRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaUTRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoMTxt;
    private javax.swing.JTextField ApellidoPTxt;
    private javax.swing.JButton BuscarBtn;
    private javax.swing.JTextField BuscarTxt;
    private javax.swing.JButton CantidadBtn;
    private javax.swing.JTextField CarreraTxt;
    private javax.swing.JButton GuardarFinalBtn;
    private javax.swing.JButton GuardarInicioBtn;
    private javax.swing.JTextArea ListaTxt;
    private javax.swing.JTextField MatriculaTxt;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JButton OrdenarBtn;
    private javax.swing.JTextArea TotalTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
